# Generated by Django 6.1 on 2026-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_favoritemovie_watchlistmovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
