# Generated by Django 6.1 on 2026-08-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series')], default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('tmdb_id', 'media_type'), name='unique_tmdb_media'),
        ),
    ]
