# Generated by Django 6.1 on 2026-08-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_media_type_alter_movie_tmdb_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('season_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('episode_count', models.PositiveIntegerField(default=0)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.movie')),
            ],
            options={
                'ordering': ['season_number'],
            },
        ),
        migrations.CreateModel(
            name='TVEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('runtime', models.PositiveIntegerField(blank=True, null=True)),
                ('still_path', models.CharField(blank=True, max_length=500)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.tvseason')),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
        migrations.CreateModel(
            name='WatchedEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='movies.tvepisode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='tvseason',
            constraint=models.UniqueConstraint(fields=('series', 'season_number'), name='unique_series_season'),
        ),
        migrations.AddConstraint(
            model_name='tvepisode',
            constraint=models.UniqueConstraint(fields=('season', 'episode_number'), name='unique_season_episode'),
        ),
        migrations.AddConstraint(
            model_name='watchedepisode',
            constraint=models.UniqueConstraint(fields=('user', 'episode'), name='unique_user_watched_episode'),
        ),
    ]
