# Generated by Django 6.1 on 2026-08-23 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_tvseason_tvepisode_watchedepisode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, choices=[('horror', 'Horror'), ('action', 'Action'), ('sci_fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('romance', 'Romance'), ('animation', 'Animation'), ('adventure', 'Adventure'), ('mystery', 'Mystery'), ('western', 'Western')], default='', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watchlibrary_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
